application: dtgoapps
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: .*/css
  static_dir: templates/css

- url: .*/fonts
  static_dir: templates/fonts

- url: .*/ico
  static_dir: templates/ico

- url: .*/img
  static_dir: templates/img

- url: .*/js
  static_dir: templates/js

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
